project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: 'SHARC'
  site-url: 'https://bienflorencia.github.io/rda-sharc-reco'
  repo-url: https://github.com/bienflorencia/rda-sharc-reco

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    left: "&copy; CC-BY [SHARC IG](https://www.rd-alliance.org/groups/sharing-rewards-and-credit-sharc-ig) (2023)"
    background: "#D9E3E4"

  sidebar:
    logo: 'images/logo.png'
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.rd-alliance.org/groups/sharing-rewards-and-credit-sharc-ig
        text: 'SHARC IG'
      - icon: github
        href: https://github.com/bienflorencia/rda-sharc-reco
        text: 'GitHub'

    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Intro
      - href:
        text: 'LEVELS'
      - href: individual.qmd
        text: (A) Individual
      - href: institutions.qmd
        text: (B) Institutions
      - href: funders.qmd
        text: (C) Funders
      - href: publishers.qmd
        text: (D) Publishers
      - href: policy-makers.qmd
        text: (E) Government policy makers
      - href: https://github.com/bienflorencia/rda-sharc-reco/discussions
        text: Contribute

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    toc: true
