project:
  type: website
  output-dir: docs

website:
  title: 'Reco-SHARC'
  sidebar:
    background: primary
    # logo: 'images/logo.png'
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bienflorencia/rda-sharc-reco
        text: GitHub
    style: docked
    contents:
      # - href: index.qmd
      #   text: Home
      # - href: schedule.qmd
      #   text: Schedule
      # - href: materials.qmd
      #   text: Materials
      - href: intro.qmd
        text: Intro
      - href: https://github.com/bienflorencia/rda-sharc-reco/discussions
        text: Contribute

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto
