project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: 'SHARC'
  site-url: 'https://bienflorencia.github.io/rda-sharc-reco'
  repo-url: https://github.com/bienflorencia/rda-sharc-reco

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    left: "&copy; CC-BY [SHARC IG](https://www.rd-alliance.org/groups/sharing-rewards-and-credit-sharc-ig/activity/) (2024)"
    background: "#D9E3E4"

  sidebar:
    logo: 'images/logo.png'
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.rd-alliance.org/groups/sharing-rewards-and-credit-sharc-ig/activity/
        text: 'SHARC IG'
      - icon: github
        href: https://github.com/bienflorencia/rda-sharc-reco
        text: 'GitHub'
      - icon: file-pdf
        href: RDA_SHARC_recos.pdf
        text: 'PDF'

    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: methodology.qmd
        text: Methodology
      - section: recommendations.qmd
        contents:
          - href: research_performing_organisations.qmd
            text: To research performing organisations
          - href: funders.qmd
            text: To funders
          - href: publishers.qmd
            text: To publishers
          - href: government-policy-makers.qmd
            text: To government policy makers
          - href: researchers.qmd
            text: To researchers
      - href: concluding_remarks.qmd
        text: 'Concluding remarks'
      - section: ---
      - href: terminology.qmd
        text: 'Terminology'
      - section: 'Mapping tools'
        contents:
          - href: mapping_tools/os_policies.qmd
          - section: 'Rewarding tools'
            contents:
            - href: mapping_tools/os_award_prizes.qmd
            - href: mapping_tools/os_funds.qmd
            - href: mapping_tools/os_badges_certificates_tokens.qmd
            - href: mapping_tools/os_champions.qmd
      - href: abbreviations.qmd
        text: Abbreviations
      - href: acknowledgements.qmd
        text: Acknowledgements
      # - href: references.qmd
      #   text: References

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    toc: false
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 0px
      gutter-width: 1.5rem
