project:
  type: website
  output-dir: docs

website:
  title: 'Reco-SHARC'
  sidebar:
    background: primary
    # logo: 'images/logo.png'
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bienflorencia/rda-sharc-reco
        text: GitHub
    style: docked
    contents:
      - href: intro.qmd
        text: Intro
      - href: individual.qmd
        text: (A) Recognition at the individual level
      - href: institutions.qmd
        text: (B) Recommendations to institutions
      - href: funders.qmd
        text: (C) Recommendations to funders
      - href: publishers.qmd
        text: (D) Recommendations to publishers
      - href: policy-makers.qmd
        text: (E) Recommendations to government policy makers
      - href: https://github.com/bienflorencia/rda-sharc-reco/discussions
        text: Contribute

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto
