---
title: 'To funders'
bibliography: references.bib
page-layout: full
---

For funders to support OS, it is important that they develop policies that require, or at a minimum, encourage OS activities in their communities and integrate them into their proposal workflows. To develop these policies, funders should gain a better understanding of current open research practices and capabilities, by conducting landscape analyses, engaging with the OS community, leveraging expertise, and identifying initial steps (i.e. low hanging fruits) that can be taken to monitor and guide these activities. Mapping key stakeholders in OS would be prudent, to avoid being overwhelmed and to interface with the OS community via these stakeholders. For reference, the Aligning Science Across Parkinson's [@asap_2021] is an example of the more forward-looking funder policies.  

OS monitoring is still a relatively new and developing aspect of the research community where organisations like CoARA and UNESCO are guiding these conversations. However, it is difficult for funders to track these conversations, and it is important for these groups to engage funders, where reasonable [e.g., @scilifelab_data_centre_2024]. For instance, to develop a common framework and schema where policy recommendations and requirements can be aligned. These communities, for the funders sake, should also work towards ensuring that the underlying sources and workflows used to provide information for monitoring and assessment are clear. Funders are limited in how they can interface with OS infrastructure, so it is important for infrastructure providers to take a simple approach to how they need funders to provide them with information (for instance, asking funders to interact with APIs or use XML vs CSV). The support of funders like Arcadia for projects such as OpenAlex [@portenoy_2024] underscores the importance of investing in collaborative, open scholarly infrastructure to be used as sources for OS monitoring. This commitment is shared by other funders, such as the Bill & Melinda Gates Foundation and the French National Research Agency, who have demonstrated their support by signing the 2024 Barcelona Declaration of Open Research Information.  

Initiatives like the national PID strategies out of RDA [@brown_2022] are helpful to funders as they outline the required infrastructure components they need to enable OS. An example is RAiD (Research Activity Identifier) which allows funders to interlink outputs and resources, but also better understand (interdisciplinary) collaboration in the projects they fund. Not every funder has the capability to implement a data management plan workflow but an output-based approach is an alternative to monitoring and assessment. In line with PIDs that make researchers outputs searchable and discoverable and guarantee their long-term accessibility and tracing, it is worth mentioning emerging decentralised PID approaches such as dPIDs [@hill_2024] and dARK [@matas_2023], as new potential monitoring systems to be explored. 

New approaches to funding OS need to be explored and implemented, where funding is allocated to support policies. These can be prizes celebrating OS aspects such as the 'DataWorks! Prize', developing 'OS champions', for instance, at Michael J. Fox Foundation (in the US), encouraging and allocating support for DMPs and data publishing like ANII (in Uruguay). Also, coordination is key as a number of funders are limited by how much they can allocate to OS versus some of the funders that are allocating more towards big initiatives and infrastructure projects. The decision regarding what to fund in OS is more often dependent on the funder's vision, mission, goals, and values.  

Supporting OS requires certain commitments from funders beyond just infrastructure. Diversity, Equity, Inclusion, and Accessibility (DEIA) should be integrated into programs together with fostering team science, collaboration, and greater transparency, in line with the CARE principles [@russo_carroll_care_2020]. These are key tenets of OS, but it is also important that funders look at which principles and values are important to them and how they align with OS (e.g., supporting preprints and open access for the public good). These principles and values can be used as a compass to help with guiding funders through a dynamic OS landscape. Funders should look internally too on how they dedicate staff time and resources to support OS (e.g., setting up teams and roles). 

<br>

### Table 2: Recommendations to Funders

```{r}
#| message: false
#| echo: false

library(reactable)
library(tidyverse)

table <- read_csv('tables/table2_recos_to_funders.csv') %>% 
  janitor::clean_names() %>% 
  mutate(across(1:3, ~ str_trim(.)))

reactable(table %>% set_names(~ str_to_sentence(.) %>%
                  str_replace_all('_', ' ')) %>% 
            mutate(Url = str_to_lower(Url)) %>% 
            rename(URL=Url), 
          resizable = TRUE,
          defaultPageSize = 60,
          wrap = TRUE,
          outlined = TRUE,
          striped = TRUE, searchable = TRUE,
          defaultColDef = colDef(minWidth = 100),
          columns = list(
            URL = colDef(cell = function(value) 
            { if(is.na(value)) {
              ''
            } else{
              htmltools::tags$a(href = value,
                                target = "_blank", value)
              }
            }),`Recommended action` = colDef(minWidth = 200))
)
```

