---
title: 'To government policy makers'
bibliography: references.bib
page-layout: full
---

The governments' adoption and promotion of a national OS policy are an important driver for its implementation. It demonstrates political willingness and helps facilitate the harmonisation of practices across a variety of institutions and disciplines: giving common guidelines and a roadmap to all universities and research institutes facilitates a consistent uptake of OS across territory, institutes and disciplines. Some countries have been early in setting up a national OS strategy [@sveinsdottir_2021], and a few of them have included rewarding mechanisms such as France [@mesr_2021] and the Netherlands [@npos_2022]. In the French national OS plan, a number of measures are mentioned to make OS practices sustainable, among them the requirement for changes in the evaluation system. In the Dutch national OS strategy, a requirement for realising OS is to 'Make OS rewarding through incentives (Recognition & Rewards)'. 

It is important to recognise that international reference texts such as the UNESCO Recommendation on OS [@unesco_2021] have stimulated such national strategies and policies. By the end of 2023, eleven countries had national policies stemming from UNESCO's OS recommendations (Austria, Colombia, Cyprus, Ireland, Italy, Latvia, Lesotho, Romania, South Africa, Spain and Ukraine), so the number of countries having such national policies had doubled since the recommendation. Four countries included OS principles in their national Science Technology and Innovation policies (Estonia, Ghana, Sierra Leone and Slovenia); eleven countries (Botswana, Côte d'Ivoire, Croatia, Kenya, Mozambique, Namibia, Nigeria, Somalia, United Republic of Tanzania, Uganda and Venezuela) are currently developing OS policies taking into account the UNESCO recommendation though not specifically mentioning rewarding and crediting measures [@unesco_2023]. 

Our overarching recommendation is for governments to develop national OS policies. Table 4 gives examples of such national strategies in various countries that policymakers can adapt to their own contexts. Considering such policies, a number of specific elements need attention.  

First, incorporating effective reward mechanisms into national OS policies is important. Providing clear incentives is needed, as opposed to framing OS activities as burdensome requirements. These incentives are vital for fostering the acceptance and successful implementation of OS policies within the scientific community.  

Second, compiling and documenting use cases via dedicated websites would highlight real-life mechanisms that have been implemented or piloted. Given the substantial diversity among institutions and policies across various domains and contexts, it is clear that rewarding different scientific activities is not a 'one size fits all' effort. Showcasing use cases would accelerate the implementation of systems that work effectively across most domains. At the same time, it would accommodate specific mechanisms where necessary. Additionally, it would help avoid repeating mistakes or duplicating efforts.   

Third, systematic and rigorous approaches to analyse OS activities, particularly reward mechanisms, are needed. The French national OS plan, for example, has launched a specific call for research proposals in 2023 to study OS activities, including reward systems. To achieve a comprehensive understanding, we recommend prioritising and encouraging funding for projects dedicated to the in-depth analysis of these mechanisms or providing direct funding for such research initiatives.  

Finally, it is often the case that various practices are established and tools or mechanisms are tested, but this is frequently done in silos, without coordination between institutions. At the national level, such coordination can be organised and highlighted. Thus, facilitating networking and sharing of practices across institutions at the national level is highly recommended. Further, despite international initiatives such as RDA and CoARA that are pivotal for harmonising assessment methods and mechanisms, there is still a notable lack of dedicated efforts to standardise the assessment of rewards for OS activities at the national level across various institutions and disciplines. Addressing this gap should be a priority to advance OS on a global scale.  


<br>

### Table 4: Recommendations to Government policy makers

```{r}
#| message: false
#| echo: false

library(reactable)
library(tidyverse)

table <- read_csv('tables/table4_recos_to_government_policy_makers.csv') %>% 
  janitor::clean_names() %>%
  mutate(across(1:3, ~ str_squish(str_trim(.))))

reactable(table %>% set_names(~ str_to_sentence(.) %>%
                  str_replace_all('_', ' ')) %>% 
            mutate(Url = str_to_lower(Url)) %>% 
            rename(URL=Url), 
          resizable = TRUE,
          defaultPageSize = 60,
          wrap = TRUE,
          outlined = TRUE,
          striped = TRUE, searchable = TRUE,
          defaultColDef = colDef(minWidth = 100),
          columns = list(
            URL = colDef(cell = function(value) 
              { htmltools::tags$a(href = value, 
                                  target = "_blank", value)
              }),
            `Recommended action` = colDef(minWidth = 200)
            )
)
```
