---
title: 'Recommendations on Open Science Rewards and Incentives '
subtitle: 'Guidance for multiple stakeholders in Research'
page-layout: full
authors:
  - name: Laurence Mabile
    orcid: 0000-0002-7724-1721
    email: laurence.mabile@univ-tlse3.fr
  - name: Hanna Shmagun
    orcid: 0000-0001-6271-2976
  - name: Christopher Erdmann
    orcid: 0000-0003-2554-180X
  - name: Anne Cambon-Thomsen
    orcid: 0000-0001-8793-3644
  - name: Mogens Thomsen
    orcid: 0000-0002-4546-0129
  - name: Florencia Grattarola
    orcid: 0000-0001-8282-5732
---

Open Science contributes to the collective building of scientific knowledge and societal progress. However, academic research currently fails to recognise and reward efforts to share research outputs. Yet it is crucial that such activities be valued, as they require considerable time, energy, and expertise to make scientific outputs usable by others, as stated by the FAIR principles. To address this challenge, several bottom-up and top-down initiatives have emerged to explore ways to assess and credit Open Science activities (e.g., Research Data Alliance, RDA) and to promote the assessment of a broad spectrum of research outputs, including datasets and software (e.g., Coalition for Advancement of Research Assessment, CoARA). As part of the RDA-SHARC (SHAring Rewards and Credit) interest group, we have developed a set of recommendations to help implement various rewarding schemes at different levels. The recommendations target a broad range of stakeholders. For instance, institutions are encouraged to provide digital services and infrastructure, organise training and cover expenses associated with making data available for the community. Funders should establish policies requiring open access to data produced by funded research and provide corresponding support. Publishers should favour open peer-review models and open access to articles, data and software. Government policymakers should set up a comprehensive Open Science strategy, as recommended by UNESCO and followed by a growing number of countries. The present work details different measures that are proposed to the stakeholders. The need to include sharing activities in research evaluation schemes as an overarching mechanism to promote Open Science practices is specifically emphasised.

**Keywords**: Open Science, Open Access, FAIR, rewards, sharing, research evaluation
