---
title: 'Introduction'
bibliography: references.bib
#suppress-bibliography: true
---

## Why open science is important

Science is a cumulative process [@merton_1973] that relies on previous knowledge considering all types of research outputs [@dasgupta_1994; @walsh_2007]. Although sharing research outputs as common goods should be the common rule, this is actually not the case. 

The Open Science (OS) movement was forged in response to this concern. It refers to a range of activities [@grattarola_2024] including sharing research outputs. OS enables replication, improves productivity, limits redundancy, and helps create more robust research methods and a rich network of resources, thus increasing research efficiency [@murray_2007; @walsh_2007; @shibayama_2011]. In the end, it contributes to the collective building of scientific knowledge and societal progress [@cole_2024]. 

## How modern science is recognised

To appreciate any contribution to science, credit and recognition are a prerequisite to any 'reward mechanism' and need to be mapped in the overall research assessment scheme. Crediting is the explicit recognition for one's contribution to a work, the process whereby ownership of a scientific work is attributed to an individual, a group of individuals or an institution [@merton_1973; @shibayama_2011; @walsh_2007]. It is the first step in recognising the value of one's work and is generally quantified by a series of metrics. It is an important process which builds scientists' reputation. Crediting can be seen as a milestone in the process of rewarding which encompasses several elements such as academic promotion, grants, dedicated staff and support materials that help produce subsequent discoveries [@latour_1979; @shibayama_2021]. In the case of published discoveries, credit is allocated by the community through attribution, peer review, and citation. It can also come from patenting in some specific cases [@allea_2023]. Sharing intermediate or pre-publication outputs is however far less established as it is more complex and does not necessarily fit into the conventional crediting system of science [@shibayama_2021]. A number of studies have underlined that academic research fails to recognise, value, and reward efforts to open up the scientific process [@hicks_2015; munafo_2017; wilsdon_2015; wouters_2015]. Yet it is crucial that these activities be valued as they require considerable time, energy and expertise to make outputs findable and accessible and for data and software to be compliant with international standards making them interoperable and reusable by others, as stated by the FAIR principles [@wilkinson_2016]. 

## The current sharing practice of academics

In the 'publish or perish' culture, some outputs (such as data, databases, or algorithms) may provide academics with an advantage under high competition which can lead them not to share those [@merton_1973; @dasgupta_1994; @haas_2010; @haeussler_2014]. Moreover, some commercialisation contexts, regulatory constraints, privacy issues or data reuse concerns as well as shortage of funds, lack of time or of capacities and technical resources, could also be barriers [@haas_2010; @walsh_2007]. As a result, the amount of outputs shared through open mechanisms is still limited in many communities or disciplines, and a lot of resources are shared in one-to-one transactions [@shibayama_2011; @tenopir_2015; @wallis_2013]. Thus, the degree of openness is still mainly at the discretion of individual academics [@blume_1974; @hackett_2008; @nelson_2016]. However, academics broadly agree that open sharing is beneficial to science and numerous studies showed that when requested, it is respected [@czarnitzki_2015; @haas_2010; @shibayama_2011; @walsh_2007]. Now a clear consensus on how outputs should be shared and rewarded, needs to be established.  

## The current normative incentives for sharing

Since the Budapest Declaration [@boai_2002], that specifically propelled the Open Access (OA) concept, governments, funders, research organisations and publishers are increasingly adopting formal OS policies [@manco_2022] with a primary focus on OA to publications and underlying research data. Pioneers in adopting such policies include, for example, Scientific Electronic Library Online (SciELO), the National Institutes of Health (NIH), White House's Office of Science and Technology Policy (OSTP), Gates Foundation, Wellcome Trust, UK research councils, Harvard University and Queensland University of Technology. In spite of this, the sharing activities are often not sufficiently recognised or credited in formal assessments of researchers and project proposals, discouraging researchers from engaging in sharing activities [@arthur_2021].   

Efforts to address this challenge have led to the rise of several initiatives within the Responsible Research Assessment (RRA) movement. Notable examples are the DORA declaration [@dora_2012], the Dutch initiative 'Science in Transition' [@dijstelbloem_2013], the Leiden Manifesto [@hicks_2015] and the Metric Tide [@wilsdon_2015]. While these initiatives have not directly focused on recognising and rewarding OS practices, they have significantly contributed to promoting responsible metrics and the assessment of a broad spectrum of research outputs, including datasets and software.  

The most notable initiatives that explicitly incorporated OS into the RRA discourse have emerged in the European Union. For example, the European Commission established a Working Group in 2016 on rewards under OS that formulated the OS Career Assessment Matrix (OS-CAM), suggesting various criteria for incorporating OS activities in the formal evaluations of researchers at all career stages [@eu_commission_2017]. Moreover, the European Research Area Policy Agenda for 2022-2024 [@ec_dgri_2021] has set the transformation of research assessment systems as a priority strategic action, including the rewarding of OS practices as part of this necessary change, further supported by the *Conclusions of the Council of the European Union on Research Assessment and Implementation of OS* [@eu_council_2022]. In line with this agenda, the Coalition for Advancing Research Assessment [@coara_2022] was formed in 2022, as an initiative from several European organisations, bringing together stakeholders from the research ecosystem across 164 countries to enhance and harmonise research assessment practices, with an emphasis on recognising and rewarding behaviours underpinning OS activities. Additionally, the Horizon Europe programme has incorporated OS into its evaluation of all research proposals and project assessments, showcasing a prime example of how these practices can be embedded in funder evaluation schemes [@eu_aga_2023; @eu_parliament_and_council_2021]. Also, the ongoing Horizon Europe 'GraspOS' project [@eu_horizon_ria_graspos_project_2023] has been specifically designed to support the emerging policy reforms and bring about the adoption of a RRA system that embeds OS practices, by developing federated infrastructure and tools. Lastly, cOAlition S funders, including the European Commission, have recently introduced a proposal named 'Towards Responsible Publishing' [@coalition_s_2023], which calls for the incorporation of OS practices into funders' assessment policies and the elimination of journal metrics in the evaluation of researchers. 

Some countries have also initiated steps to integrate OS practices into their research assessment schemes, with notable efforts seen in the Netherlands [@vnsu_2019], France [@cnrs_2019], Norway [@uhr_working_group_2021], Finland [@working_group_for_responsible_evaluation_of_a_researcher_2020] and in Latin America and the Caribbean [@clacso_2019]. Details and more initiatives are given by @rijcke_2023. Simultaneously, bottom-up international initiatives have emerged to explore more immediate ways to assess and credit OS activities. Notably, the data science community is getting organised under the umbrella of the Research Data Alliance (RDA) to articulate related concerns and offer recommendations (e.g., [RDA-SHARC Interest Group](https://www.rd-alliance.org/groups/sharing-rewards-and-credit-sharc-ig/members/all-members/), [RDA-Research Evaluation Interest Group](https://www.rd-alliance.org/groups/evaluation-research-ig/members/all-members/), and [CODATA working groups](https://codata.org/initiatives/working-groups/)). 


## Objective

In this paper, we provide a set of recommendations developed by the RDA-SHARC interest group to help implement various rewarding schemes for opening up science. These recommendations specifically emphasise the need to include sharing activities in research evaluation schemes as an overarching, valuable, and hopefully efficient mechanism to promote OS practices. The recommendations target a broad range of stakeholders in research and innovation systems, as highlighted by the UNESCO Recommendation on OS [@unesco_2021], emphasising the collaborative effort of individual researchers, research institutions, funders, government policymakers and publishers in transforming the research culture towards OS [@nosek_2023].  
