---
title: 'To researchers'
bibliography: references.bib
csl: apa-6th-edition.csl
page-layout: full
---

At the individual level and in the current research ecosystem, getting some kind of reward from OS activities will result from several distinct mechanisms that people must be aware of. 

First, the normative context framing one's research activity, e.g. in particular national and institutional ones if existent, sets the tone for what must, can or should be done, and sometimes describes how. It is then imperative that everyone is aware of the policies and regulations in place and of the possible means accompanying their implementation. More and more, OS frameworks are endorsed over time worldwide and may provide opportunities to get/apply for various kinds of training and support (material, financial, human). For instance, through specific funds, prizes or awards (see SHARC's [OS Awards/Prizes](mapping_tools/os_award_prizes), [OS Funds](mapping_tools/os_funds)), or by anticipating an OS budget in the funding applications. Researchers need to watch over this evolving context to anticipate assignments and seize opportunities. 

Second, a number of actions are necessary to maximise one's digital presence and visibility on the basis of crediting processes in research [detailed in @stall_parsec_2023]. The prerequisite for crediting is an identification scheme for researchers and their work's outputs that is unambiguous, persistent and embedded in the scholarly digital ecosystem. The attribution of a PID with associated rich metadata to a research object, makes it searchable and discoverable and guarantees its long-term accessibility and tracing. This is easily achievable for datasets or databases that are numerical by nature. Regarding physical/material resources, it requires first that their description is somehow digitised and accessible on the web (e.g., via metadata-only datasets, data papers or landing pages). Identification through PIDs is now supported by robust organisations, especially DataCite operating DOIs for numerical objects and ORCID for individual researchers. Making visible those identified elements is the next step to getting or giving credit. It is essential that researchers refer systematically to all their own OS-identified outputs wherever relevant through citation and/or acknowledgement, notably in papers, CVs and reporting activities. It is equally essential that researchers cite or acknowledge other's outputs they reuse in their own research. This is also intrinsically linked with how co-authorship is managed within projects/teams. It is important to consider the diverse contributor roles and it is advised to establish how to handle co-authorships from the beginning of a project to ensure that everyone's contribution (including e.g., technicians or data collectors) is included. 

Thirdly, obtaining symbolic rewards such as OS badges and certificates or OS ambassador roles can serve as a form of recognition for researchers who engage in OS practices (e.g., Open Science Badges of the Center for Open Science). These recognition schemes can help build trust in the researchers' work and enhance their credibility as researchers [@schneider_2022]. By earning badges, researchers demonstrate their commitment to OS and become visible in their community for that. Having digital badges incorporated into an author's record as a contribution to overall metrics is to be explored and implemented in research scholarly infrastructures. More practical information is provided in Table 5.

Finally, credit/recognition can also be obtained for research outputs that have a commercial perspective through patents that may have been obtained based on the results. Obtaining patents means that researchers or their employer legally own intellectual property rights. Researchers should be aware that patenting and OS practices are compatible [@ec_innovation_council_and_smes_executive_agency_2023], i.e. open sharing of findings can be done as soon as a patent application is filed or prior to the filing in certain jurisdictions such as the US and South Korea which provide 'grace periods' [@nuechterlein_2023]. In such cases, advice should be given to the applicant that they should encourage the 'free non-commercial use by [other] researchers of knowledge disclosed in patents'. Given that large, detailed and consistent datasets are an asset not only for researchers but also for companies, monetary reward opportunities can arise to provide incentives for data sharing [@allea_2022]. 

For examples on national and institutional OS plans, OS and FAIR awards, dedicated funds for OS, and training initiatives, please refer to our Rewarding tools ([OS Awards/Prizes](mapping_tools/os_award_prizes), [OS Funds](mapping_tools/os_funds), [OS Badges/Certificates/Tokens](mapping_tools/os_badges_certificates_tokens), [OS Champions](mapping_tools/os_champions)).

<br>

### Table 5: Recommendations to Researchers

```{r}
#| message: false
#| echo: false

library(reactable)
library(tidyverse)

table <- read_csv('tables/table5_recos_to_researchers.csv') %>% 
  janitor::clean_names() %>% 
  mutate(across(1:3, ~ str_trim(.)))

reactable(table %>% set_names(~ str_to_sentence(.) %>%
                  str_replace_all('_', ' ')) %>% 
            # mutate(Url = str_to_lower(Url)) %>% 
            rename(URL=Url), 
          resizable = TRUE,
          defaultPageSize = 60,
          wrap = TRUE,
          outlined = TRUE,
          striped = TRUE, searchable = TRUE,
          defaultColDef = colDef(minWidth = 100),
          columns = list(
            URL = colDef(cell = function(value) 
            { 
              htmltools::tags$a(href = value,
                                target = "_blank", value)
            }),
            `Recommended action` = colDef(minWidth = 200))
)
```
